---
title: "Example Quarto Document"
author: "Amin G. Alhashim (aalhashi@macalester.edu)"
date: "9/7/2024"
---


## Load Packages


Load all required packages


```{r}
#| include: true
#| echo: false


library(readxl)
library(dplyr)
```




## Import Data


Load *Airbnb Listing in New York City* dataset from [tableau website](https://public.tableau.com/app/learn/sample-data).


```{r}
#| include: true
#| echo: true


ds <- read_xlsx("https://public.tableau.com/app/sample-data/airbnb.xlsx")
```




## Explore Data


Show what the dataset consists off


```{r}
#| include: true
#| echo: true


# this is an example of non-code answer in the code chunk
glimpse(ds)
```




## Some Long Visualization


This section illustrate how to comment a code chunk when it is very long


```{r}
#| include: true
#| echo: true


# action 1
<some code>


# action 2
<more code>


# action 3
<more code>
```


## References


- Tableau Sample Datasets, https://public.tableau.com/app/learn/sample-data, (accessed: September 7, 2024)
